const { loadConfig } = require('../config');
const c = loadConfig();
const hasConfigKey = !!c.aiApiKey;
const envOpenrouter = !!process.env.OPENROUTER_API_KEY;
const envAi = !!process.env.AI_API_KEY;
const source = envOpenrouter ? 'OPENROUTER_API_KEY' : (envAi ? 'AI_API_KEY' : 'none');
console.log('ai key present in config:', hasConfigKey);
console.log('env OPENROUTER_API_KEY present:', envOpenrouter);
console.log('env AI_API_KEY present:', envAi);
console.log('detected source (if any):', source);
